### ISSUE TITLE
DBLP import modal css is not compiled correctly in production build generated by next.js

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-web#86]
in dblp import modal, existing publication in openreview has css class .existing-publication-row which is defined as 
```css
.existing-publication-row {
      background-color: @backgroundGray;
      opacity: 50%;
    }
```

in development it's working as expected.
![image](https://user-images.githubusercontent.com/60613434/87980660-f4925e80-caa1-11ea-86c1-e4de9e7c50df.png)

in production build , the opacity is changed to 1% and causing existing publication row to be invisible
![image](https://user-images.githubusercontent.com/60613434/87981312-09bbbd00-caa3-11ea-9b2d-97a8e40cb521.png)
